<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="finanzaspagos-20240715180303" tests="1" file=".py" time="198.313" timestamp="2024-07-15T18:06:21" failures="0" errors="1" skipped="0">
	<testcase classname="finanzaspagos" name="test_finance_payment" time="198.313" timestamp="2024-07-15T18:06:21" file="finanzasPagos.py" line="22">
		<error type="AttributeError" message="module 'datetime' has no attribute 'now'"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\finanzasPagos.py", line 129, in test_finance_payment
    verify_todate(self.driver,select_todate)
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\Elements.py", line 1622, in verify_todate
    fecha_actual = datetime.now().strftime('%Y-%m-%d')
AttributeError: module 'datetime' has no attribute 'now'
]]></error>
		<system-out><![CDATA[El texto encontrado es  Listado de Comprobantes
¡Input encontrado y enviado con éxito!
¡Input encontrado y enviado con éxito!
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
]]></system-out>
	</testcase>
</testsuite>
