<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="granos_contratos-20240311182027" tests="1" file=".py" time="52.400" timestamp="2024-03-11T18:21:19" failures="0" errors="1" skipped="0">
	<testcase classname="granos_contratos" name="test_granos_contratos" time="52.400" timestamp="2024-03-11T18:21:19" file="GranosContratos.py" line="23">
		<error type="TypeError" message="search_and_displace_account() takes 3 positional arguments but 4 were given"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones-SILOHUB-\GranosContratos.py", line 61, in test_granos_contratos
    search_and_displace_account(self.driver, account_number, select_input, select_element )
TypeError: search_and_displace_account() takes 3 positional arguments but 4 were given
]]></error>
		<system-out><![CDATA[¡Elemento encontrado y clickeado con éxito!
¡Elemento encontrado y clickeado con éxito!
El texto encontrado es  CONTRATOS
La opcion fue seleccionada con éxito después de hacer clic en el chevron!
Tiempo de espera agotado. El texto por xpaht no está presente.
¡Elemento encontrado y clickeado con éxito!
]]></system-out>
	</testcase>
</testsuite>
