<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="cta_cte_pesiFechaVevcimientoV2-20241028161403" tests="2" file=".py" time="76.763" timestamp="2024-10-28T16:15:20" failures="0" errors="2" skipped="0">
	<testcase classname="cta_cte_pesiFechaVevcimientoV2" name="test_ctacte_Date_expiration" time="0.000" timestamp="0001-01-01T00:00:00" file="ctacte_PesiFechaVenciV2.PY" line="18">
		<error type="WebDriverException" message="Message: TypeError: browsingContext.currentWindowGlobal is null
Stacktrace:
getMarionetteCommandsActorProxy/get/&lt;@chrome://remote/content/marionette/actors/MarionetteCommandsParent.sys.mjs:357:17
observe@resource://gre/modules/AsyncShutdown.sys.mjs:569:17
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\ctacte_PesiFechaVenciV2.PY", line 79, in test_ctacte_Date_expiration
    find_elements(self.driver, movements_list_2)
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\Elements.py", line 19, in find_elements
    select_nex_button = WebDriverWait(driver, 10).until(
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\wait.py", line 96, in until
    value = method(self._driver)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\support\expected_conditions.py", line 363, in _predicate
    target = driver.find_element(*target)  # grab element at locator
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 748, in find_element
    return self.execute(Command.FIND_ELEMENT, {"using": by, "value": value})["value"]
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: TypeError: browsingContext.currentWindowGlobal is null
Stacktrace:
getMarionetteCommandsActorProxy/get/<@chrome://remote/content/marionette/actors/MarionetteCommandsParent.sys.mjs:357:17
observe@resource://gre/modules/AsyncShutdown.sys.mjs:569:17

]]></error>
		<system-out><![CDATA[El texto encontrado es  CUENTA PESIFICADA
El valor no es un carácter numérico. Valor: SALDO ARS
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
]]></system-out>
	</testcase>
	<testcase classname="cta_cte_pesiFechaVevcimientoV2" name="test_ctacte_Date_expiration" time="76.763" timestamp="2024-10-28T16:15:20" file="ctacte_PesiFechaVenciV2.PY" line="18">
		<error type="InvalidSessionIdException" message="Message: WebDriver session does not exist, or is not active
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
InvalidSessionIDError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:448:5
assert.that/&lt;@chrome://remote/content/shared/webdriver/Assert.sys.mjs:515:13
assert.session@chrome://remote/content/shared/webdriver/Assert.sys.mjs:37:4
despatch@chrome://remote/content/marionette/server.sys.mjs:315:19
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/&lt;@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/&lt;@chrome://remote/content/marionette/transport.sys.mjs:494:20
"><![CDATA[Traceback (most recent call last):
  File "c:\Users\luist\repos\Automatizaciones_M-dulos-\ctacte_PesiFechaVenciV2.PY", line 143, in tearDown
    self.driver.close()
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 465, in close
    self.execute(Command.CLOSE)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\luist\AppData\Roaming\Python\Python310\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: WebDriver session does not exist, or is not active
Stacktrace:
RemoteError@chrome://remote/content/shared/RemoteError.sys.mjs:8:8
WebDriverError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:193:5
InvalidSessionIDError@chrome://remote/content/shared/webdriver/Errors.sys.mjs:448:5
assert.that/<@chrome://remote/content/shared/webdriver/Assert.sys.mjs:515:13
assert.session@chrome://remote/content/shared/webdriver/Assert.sys.mjs:37:4
despatch@chrome://remote/content/marionette/server.sys.mjs:315:19
execute@chrome://remote/content/marionette/server.sys.mjs:289:16
onPacket/<@chrome://remote/content/marionette/server.sys.mjs:262:20
onPacket@chrome://remote/content/marionette/server.sys.mjs:263:9
_onJSONObjectReady/<@chrome://remote/content/marionette/transport.sys.mjs:494:20

]]></error>
		<system-out><![CDATA[El texto encontrado es  CUENTA PESIFICADA
El valor no es un carácter numérico. Valor: SALDO ARS
Tiempo de espera agotado. El elemento no está presente o no es clickeable.
]]></system-out>
	</testcase>
</testsuite>
